#!/bin/bash

set -eo pipefail

if [[ ! -d "/var/lib/mysql/mysql" ]]
then
  if [ -z "$MYSQL_ROOT_PASSWORD" -a -z "$MYSQL_RANDOM_ROOT_PASSWORD" ]
  then
    echo >&2 'Error: database is uninitialized and password option is not specified '
    echo >&2 '  You need to specify one of MYSQL_ROOT_PASSWORD or MYSQL_RANDOM_ROOT_PASSWORD'
    exit 1
  fi

  echo 'Initializing database'
  /usr/bin/mysql_install_db --defaults-file=/etc/my.cnf
  echo 'Database initialized'

  if [ ! -z "$MYSQL_RANDOM_ROOT_PASSWORD" ]
  then
    MYSQL_ROOT_PASSWORD="$(pwgen -1 32)"
  fi

  /usr/bin/mysqld_safe --defaults-file=/etc/my.cnf --skip-syslog --skip-networking &
  pid="$!"
  echo "Started up mysqld with pid $pid"

  mysql=( mysql --protocol=socket -uroot )
  for i in {30..0}; do
    if echo 'SELECT 1' | "${mysql[@]}" &> /dev/null; then
      break
    fi
    echo 'MySQL init process in progress...'
    sleep 1
  done

  if [ "$i" = 0 ]; then
    echo >&2 'MySQL init process failed.'
    exit 1
  fi

  /usr/bin/mysqladmin -u root password "$MYSQL_ROOT_PASSWORD"
  echo "Set MySQL root password to: $MYSQL_ROOT_PASSWORD"

  /usr/bin/mysqladmin -u root -p"$MYSQL_ROOT_PASSWORD" shutdown
fi

echo
echo 'MySQL init process done. Ready for start up.'
echo